import Head from "next/head";
import styles from "@/styles/Home.module.scss";

export default function Home() {
    return (
        <>
            <Head>
                <title>Code hunter</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className={styles.navbar}>
                <ul>
                    <li>Home</li>
                    <li>About</li>
                    <li>Blogs</li>
                    <li>Contact Us</li>
                </ul>
            </nav>
        </>
    );
}
